package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type normalizationPair struct {
	Enum  string `json:"enum"`
	Value string `json:"value"`
}

type normalizationMetadata struct {
	ReplacedBy []normalizationPair `json:"replaced_by"`
}

type normalizationEnum struct {
	Name       string                           `json:"name"`
	Deprecated map[string]normalizationMetadata `json:"deprecated"`
}

// generateNormalization keeps all deprecated keys, including retired strings
// absent from values. It consumes the same verified registry as enum constants,
// but never derives replacements from those constants or guesses vocabulary.
func generateNormalization(enumsDir, outDir, contractsRef string) error {
	entries, err := os.ReadDir(enumsDir)
	if err != nil {
		return err
	}
	var definitions []normalizationEnum
	seen := make(map[string]bool)
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".json") {
			continue
		}
		path := filepath.Join(enumsDir, entry.Name())
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		var definition normalizationEnum
		if err := json.Unmarshal(data, &definition); err != nil {
			return fmt.Errorf("parsing %s: %w", path, err)
		}
		if definition.Name == "" || seen[definition.Name] {
			return fmt.Errorf("%s: missing or duplicate enum name %q", path, definition.Name)
		}
		seen[definition.Name] = true
		definitions = append(definitions, definition)
	}
	sort.Slice(definitions, func(i, j int) bool { return definitions[i].Name < definitions[j].Name })
	var b strings.Builder
	b.WriteString("// Code generated by traust-contracts codegen. DO NOT EDIT.\n")
	fmt.Fprintf(&b, "// Contracts source: %s\n\npackage enums\n\n", contractsRef)
	b.WriteString("var enumNormalizationRegistry = map[string]map[string]Normalization{\n")
	for _, definition := range definitions {
		fmt.Fprintf(&b, "%q: {\n", definition.Name)
		keys := make([]string, 0, len(definition.Deprecated))
		for key := range definition.Deprecated {
			keys = append(keys, key)
		}
		sort.Strings(keys)
		for _, value := range keys {
			metadata := definition.Deprecated[value]
			if metadata.ReplacedBy == nil {
				return fmt.Errorf("enum %q value %q: replaced_by must be a list", definition.Name, value)
			}
			fmt.Fprintf(&b, "%q: {", value)
			if len(metadata.ReplacedBy) == 0 {
				fmt.Fprintf(&b, "single: EnumValue{Enum: %q, Value: %q}, count: 1, Dropped: true", definition.Name, value)
			} else {
				b.WriteString("replacements: []EnumValue{")
				for _, pair := range metadata.ReplacedBy {
					fmt.Fprintf(&b, "{Enum: %q, Value: %q},", pair.Enum, pair.Value)
				}
				fmt.Fprintf(&b, "}, count: %d", len(metadata.ReplacedBy))
			}
			b.WriteString("},\n")
		}
		b.WriteString("},\n")
	}
	b.WriteString("}\n")
	return formatAndWrite(filepath.Join(outDir, "normalization_gen.go"), []byte(b.String()))
}
